name: fast_qr_reader_view_example
description: Demonstrates how to use the fast_qr_reader_view plugin.

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  airplane_mode_detection: ^1.0.0
  http: ^0.12.2
  provider: ^4.3.2+2
  geolocator: ^5.3.1
  web_scraper: ^0.0.6
  flutter_spinkit: ^4.1.2
  path_provider: ^1.3.0
  rxdart: ^0.22.2
  intl: ^0.16.0
  auto_size_text: ^2.1.0
  flutter_appavailability: ^0.0.21




dev_dependencies:
  flutter_test:
    sdk: flutter

  fast_qr_reader_view:
    path: ../


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flight.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
